version: "3.5"
services:
  manager:
    build:
      context: ./manager
      target: dev
    stdin_open: true
    tty: true
    command: bundle exec rails s
    volumes:
      - ./manager:/src/app
      - bundle:/bundle
    networks:
      manager-net:
    depends_on:
      - postgres
    ports:
      - 3000:3000
    extra_hosts:
      - rubygems.org:151.101.64.70
  postgres:
    image: postgres:11.2-alpine
    volumes:
      - ./postgres:/var/lib/postgresql/data
    networks:
      manager-net:

networks:
  manager-net:

volumes:
  bundle:
